name: kamino
description: ApolloTV for iOS and Android.

dependencies:
  # Core Dependencies
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.1

  # App Dependencies
  package_info: ^0.3.2
  flutter_statusbarcolor: any
  cplayer:
    #git:
    #  url: git://github.com/NBTX/apollotv_player.git
    #  ref: master
    path: ../cplayer/

dev_dependencies:
  flutter_rating: ^0.0.1
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.6.1"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/no_image_detail.jpg
    - images/header.png
    - images/easteregg/background.jpg
    - images/easteregg/socks.png


  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: fonts/GlacialIndifference-Regular.otf
        - asset: fonts/GlacialIndifference-Bold.otf
          weight: 700
        - asset: fonts/GlacialIndifference-Italic.otf
          style: italic
    - family: apollotv-icons
      fonts:
        - asset: fonts/apollotv-icons.woff

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

# Set app icons
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  image_path_android: "images/logo_android.png"
  image_path_ios: "images/logo_ios.png"
  adaptive_icon_background: "#FF8147FF"
  adaptive_icon_foreground: "images/logo_foreground.png"